
CREATE(u1:User {name:"Arthur"}),
(u2:User {name:"Bianca"}),
(u3:User {name:"Carolina"}),
(u4:User {name:"Daniela"}),
(u5:User {name:"Eduardo"}),
(u6:User {name:"Flávia"}),
(u7:User {name:"Giovana"}),
(u8:User {name:"Helena"}),
(u9:User {name:"Juliana"}),
(u10:User {name:"Karen"})

CREATE(s1:Serie {name:"Smallville"}),
(s2:Serie {name:"The Office"}),
(s3:Serie {name:"Animal Kingdom"}),
(s4:Serie {name:"Riverdale"}),
(s5:Serie {name:"The Rookie"}),
(s6:Serie {name:"Outlander"}),
(s7:Serie {name:"Teen Wolf"}),
(s8:Serie {name:"The Walking Dead"}),
(s9:Serie {name:"Casa da Gaby"}),
(s10:Serie {name:"Our Living World"})

CREATE(m1:Movie {name:"Eu Sou a Lenda"}),
(m2:Movie {name:"Vestida para Casar"}),
(m3:Movie {name:"Relatos do Mundo"}),
(m4:Movie {name:"Drácula"}),
(m5:Movie {name:"Dinheiro Suspeito"}),
(m6:Movie {name:"A Última Música"}),
(m7:Movie {name:"A Barraca do Beijo"}),
(m8:Movie {name:"O Exorcista"}),
(m9:Movie {name:"Matilda"}),
(m10:Movie {name:"O Dilema das Redes"})

CREATE(g1:Genre {name:"Ação"}),
(g2:Genre {name:"Comédia"}),
(g3:Genre {name:"Drama"}),
(g4:Genre {name:"Fantasia"}),
(g5:Genre {name:"Policial"}),
(g6:Genre {name:"Romance"}),
(g7:Genre {name:"Teen"}),
(g8:Genre {name:"Terror"}),
(g9:Genre {name:"Infantil"}),
(g10:Genre {name:"Documentário"})

CREATE(a1:Actor {name:"Tom Welling"}),
(a2:Actor {name:"Steve Carell"}),
(a3:Actor {name:"Finn Cole"}),
(a4:Actor {name:"KJ Apa"}),
(a5:Actor {name:"Nathan Fillion"}),
(a6:Actor {name:"Caitríona Balfe"}),
(a7:Actor {name:"Tyler Posey"}),
(a8:Actor {name:"Andrew Lincoln"}),
(a9:Actor {name:"Laila Lockhart"}),
(a10:Actor {name:"Cate Blanchett"}),
(a11:Actor {name:"Will Smith"}),
(a12:Actor {name:"Katherine Heigl"}),
(a13:Actor {name:"Tom Hanks"}),
(a14:Actor {name:"Gary Oldman"}),
(a15:Actor {name:"Chiara Mastroianni"}),
(a16:Actor {name:"Miley Cyrus"}),
(a17:Actor {name:"Joey King"}),
(a18:Actor {name:"Linda Blair"}),
(a19:Actor {name:"Mara Wilson"}),
(a20:Actor {name:"Tristan Harris"})

CREATE(d1:Director {name:"Alfred Gough"}),
(d2:Director {name:"Greg Daniels"}),
(d3:Director {name:"Jonathan Lisco"}),
(d4:Director {name:"Roberto Aguirre-Sacasa"}),
(d5:Director {name:"Alexi Hawley"}),
(d6:Director {name:"Ronald D. Moore"}),
(d7:Director {name:"Jeff Davis"}),
(d8:Director {name:"Frank Darabont"}),
(d9:Director {name:"Gaby Estrella"}),
(d10:Director {name:"Sophie Todd"}),
(d11:Director {name:"Francis Lawrence"}),
(d12:Director {name:"Anne Fletcher"}),
(d13:Director {name:"Paul Greengrass"}),
(d14:Director {name:"Francis Ford Coppola"}),
(d15:Director {name:"Olivier Masset-Depasse"}),
(d16:Director {name:"Julie Anne Robinson"}),
(d17:Director {name:"Vince Marcello"}),
(d18:Director {name:"William Friedkin"}),
(d19:Director {name:"Danny DeVito"}),
(d20:Director {name:"Jeff Orlowski"})

CREATE(a1)-[:ACTED_IN]->(s1),
(a2)-[:ACTED_IN]->(s2),
(a3)-[:ACTED_IN]->(s3),
(a4)-[:ACTED_IN]->(s4),
(a5)-[:ACTED_IN]->(s6),
(a6)-[:ACTED_IN]->(s6),
(a7)-[:ACTED_IN]->(s7),
(a8)-[:ACTED_IN]->(s8),
(a9)-[:ACTED_IN]->(s9),
(a10)-[:ACTED_IN]->(s10),
(a11)-[:ACTED_IN]->(m1),
(a12)-[:ACTED_IN]->(m2),
(a13)-[:ACTED_IN]->(m3),
(a14)-[:ACTED_IN]->(m4),
(a15)-[:ACTED_IN]->(m5),
(a16)-[:ACTED_IN]->(m6),
(a17)-[:ACTED_IN]->(m7),
(a18)-[:ACTED_IN]->(m8),
(a19)-[:ACTED_IN]->(m9),
(a20)-[:ACTED_IN]->(m10)

CREATE (d1)-[:DIRECTED]->(s1),
(d2)-[:DIRECTED]->(s2),
(d3)-[:DIRECTED]->(s3),
(d4)-[:DIRECTED]->(s4),
(d5)-[:DIRECTED]->(s5),
(d6)-[:DIRECTED]->(s6),
(d7)-[:DIRECTED]->(s7),
(d8)-[:DIRECTED]->(s8),
(d9)-[:DIRECTED]->(s9),
(d10)-[:DIRECTED]->(s10),
(d11)-[:DIRECTED]->(m1),
(d12)-[:DIRECTED]->(m2),
(d13)-[:DIRECTED]->(m3),
(d14)-[:DIRECTED]->(m4),
(d15)-[:DIRECTED]->(m5),
(d16)-[:DIRECTED]->(m6),
(d17)-[:DIRECTED]->(m7),
(d18)-[:DIRECTED]->(m8),
(d19)-[:DIRECTED]->(m9),
(d20)-[:DIRECTED]->(m10)

CREATE(s1)-[:IN_GENRE]->(g4),
(s2)-[:IN_GENRE]->(g2),
(s3)-[:IN_GENRE]->(g3),
(s4)-[:IN_GENRE]->(g7),
(s5)-[:IN_GENRE]->(g5),
(s6)-[:IN_GENRE]->(g6),
(s7)-[:IN_GENRE]->(g7),
(s8)-[:IN_GENRE]->(g8),
(s9)-[:IN_GENRE]->(g9),
(s10)-[:IN_GENRE]->(g10)

CREATE(m1)-[:IN_GENRE]->(g1),
(m2)-[:IN_GENRE]->(g6),
(m3)-[:IN_GENRE]->(g3),
(m4)-[:IN_GENRE]->(g8),
(m5)-[:IN_GENRE]->(g5),
(m6)-[:IN_GENRE]->(g6),
(m7)-[:IN_GENRE]->(g2),
(m8)-[:IN_GENRE]->(g8),
(m9)-[:IN_GENRE]->(g9),
(m10)-[:IN_GENRE]->(g10)

CREATE(u1)-[:WATCHED {RATING: 9}]->(m1),
(u2)-[:WATCHED {RATING: 3}]->(m2),
(u3)-[:WATCHED {RATING: 10}]->(s1),
(u4)-[:WATCHED {RATING: 4}]->(s4),
(u5)-[:WATCHED {RATING: 6}]->(s2),
(u6)-[:WATCHED {RATING: 8}]->(m6),
(u7)-[:WATCHED {RATING: 9}]->(s7),
(u8)-[:WATCHED {RATING: 10}]->(s6),
(u9)-[:WATCHED {RATING: 4}]->(m7),
(u10)-[:WATCHED {RATING: 10}]->(s8)


